### ISSUE TITLE
xdg-open does not work inside flatpak

### ISSUE THREAD

**Issue by jh-devv** [hyprwm/xdg-desktop-portal-hyprland#195]
This results in e.g. flatpak not opening links.

With both `xdph` and the `xdpg` installed, it will prompt the "No available application found" screen....

When only `xdph` is installed, nothing happens??

**Comment by jh-devv** [comment]
Is this an `xdg-desktop-portal flatpak` issue then?

Cause the gtk one works just fine...

**Comment by vaxerski** [comment]
xdph doesn't handle xdg-open

**Comment by jh-devv** [comment]
Actually, the exact error is:
```
GDBus.Error.org.freedesktop.DBus.Error.
UnknownMethod: No such
interface "org.freedesktop.portal.OpenURI" on object at path /org/
freedesktop/portal/desktop
````
What does provide OpenURI? Is it like.... only the gtk one?

And if I use the both the gtk one, and the xdg one.... some stuff just breaks?

**Comment by jh-devv** [comment]
This also seems to happen on some gnome applications?

**Comment by jh-devv** [comment]
If anyone else has this issue:
```sh
systemctl --user import-environment PATH```
in the hyprland startup file fixed this!

**Comment by seyfu-t** [comment]
@jh-devv  importing PATH didn't fix it for me

strange thing is, opening links inside flatpaks used to work, after upgrading my whole system (arch btw) it suddenly stopped and I can't figure out what the cause is

When trying to open a link in the flatpak edition of Evolution  I get 
```
GDBus.Error:org.freedesktop.DBus.Error.UnkownMethod:
No such interface "org.freedesktop.portal.OpenURI" on object at path /org/freedesktop/portal/desktop
```

I have xdg-desktop-portal xdg-desktop-portal-hyprland installed and none other, and I can't explain how with only these two opening URLs worked at all and why it has stopped
