### ISSUE TITLE
why does wf-recorder no need to prompt to allow for recording

### ISSUE THREAD

**Issue by littleblack111** [hyprwm/xdg-desktop-portal-hyprland#284]

**Comment by DADA30000** [comment]
because it's not using your compositor to get something from screen, it's using some driver interface afaik, but it also should ask for root password to do that, but I think that your distribution just did setcap on it

**Comment by littleblack111** [comment]
but hyprland can give info about it being recorded(seen in the second socket of screencast)

**Comment by DADA30000** [comment]
> but hyprland can give info about it being recorded(seen in the second socket of screencast)

what?

**Comment by littleblack111** [comment]
which part do u not understand?

the second socket exposed by hyprland give those infomation...

> because it's not using your compositor to get something from screen, it's using some driver interface afaik, but it also should ask for root password to do that, but I think that your distribution just did setcap on it
that is the case with gpu-screen-recorder

**Comment by vaxerski** [comment]
wf-recorder directly connects to the compositor, instead of going via XDP. Any app that is not sandboxed can do this, but the protocols for screensharing are different between compositors, so most apps don't bother.

There is a prompt gate planned for the raw protocol access too, but idk when that will be done
